[package]
name = "signalbool"
version = "0.1.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
license = "BSD-3-Clause"
keywords = ["signal", "SIGINT"]
description = "Simple signal handler for Rust projects"
documentation = "https://docs.rs/signalbool"
homepage = "https://github.com/lilydjwg/rust-signalbool"
repository = "https://github.com/lilydjwg/rust-signalbool"

[dependencies]
nix = "0.8"
